"""Market snapshot: single-row table holding pre-computed market dashboard payload."""
from datetime import datetime

from sqlalchemy import DateTime, ForeignKey, Integer, Text
from sqlalchemy.orm import Mapped, mapped_column

from app.core.db import Base


class MarketSnapshot(Base):
    """One live row with id=1 holding the latest pre-computed market analytics.

    The `payload` column stores the full JSON (global breadth + by_index +
    sectors + movers + treemap + rsi_distribution). Generated by
    `market_stats_service.recompute_snapshot` at the end of each scan run.
    """

    __tablename__ = "market_snapshot"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    computed_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    stocks_total: Mapped[int] = mapped_column(Integer, nullable=False)
    stocks_with_data: Mapped[int] = mapped_column(Integer, nullable=False)
    payload: Mapped[str] = mapped_column(Text, nullable=False)
    scan_run_id: Mapped[int | None] = mapped_column(
        Integer, ForeignKey("scan_runs.id", ondelete="SET NULL"), nullable=True
    )
