import { useQuery } from "@tanstack/react-query";

import { scores } from "@/api/scores";

/** The point-in-time IC study of the Qualità pillars. A static, rarely-changing
 *  artifact, so cache very generously; `enabled` defers the fetch until the
 *  collapsible Settings panel is first opened. */
export function useScoreIcReport(enabled = true) {
  return useQuery({
    queryKey: ["scores", "ic-report"],
    queryFn: scores.icReport,
    enabled,
    staleTime: 24 * 60 * 60_000, // 24h — regenerated by hand, months apart
    gcTime: 24 * 60 * 60_000,
  });
}
