/* GENERATO da backend/app/scripts/genera_tipi_frontend.py — non modificare.
 *
 * Per ogni tipo scritto a mano che ha un modello del server, `tsc` pretende
 * che il tipo NON dichiari campi che il server non manda (FA-111). Le
 * eccezioni, ognuna con la sua ragione, stanno nello script. */
/* eslint-disable */
import type * as S from "./schema.gen";
import type * as M0 from "@/api/alerts";
import type * as M1 from "@/api/dashboard";
import type * as M2 from "@/api/drawings";
import type * as M3 from "@/api/planOutcomes";
import type * as M4 from "@/api/platformHealth";
import type * as M5 from "@/api/preferiti";
import type * as M6 from "@/api/types";
import type * as M7 from "@/hooks/useCatalogStatus";
import type * as M8 from "@/hooks/useEquityCurve";
import type * as M9 from "@/hooks/useLiveAssets";
import type * as M10 from "@/hooks/useLiveUniverseMovers";
import type * as M11 from "@/hooks/useMarketDetail";
import type * as M12 from "@/hooks/useMultiTfKpis";
import type * as M13 from "@/hooks/useRulePerformance";
import type * as M14 from "@/hooks/useScanLog";
import type * as M15 from "@/hooks/useSectorDetail";
import type * as M16 from "@/hooks/useSetups";

type SoloNelFrontend<F, S> = Exclude<keyof F, keyof S>;
type Nessuno<T extends never> = T;

export type _M0_ConfluenceComponent = Nessuno<SoloNelFrontend<M0.ConfluenceComponent, S.ConfluenceComponentOut>>;
export type _M0_Confluence = Nessuno<SoloNelFrontend<M0.Confluence, S.ConfluenceOut>>;
export type _M1_PremarketMover = Nessuno<SoloNelFrontend<M1.PremarketMover, S.PremarketMoverOut>>;
export type _M1_PremarketMovers = Nessuno<SoloNelFrontend<M1.PremarketMovers, S.PremarketMoversOut>>;
export type _M2_StockDrawings = Nessuno<SoloNelFrontend<M2.StockDrawings, S.StockDrawingsOut>>;
export type _M3_PlanOutcomeRow = Nessuno<SoloNelFrontend<M3.PlanOutcomeRow, S.PlanOutcomeRowOut>>;
export type _M3_PlanOutcomeSummary = Nessuno<SoloNelFrontend<M3.PlanOutcomeSummary, S.PlanOutcomeSummaryOut>>;
export type _M3_PlanOutcomeList = Nessuno<SoloNelFrontend<M3.PlanOutcomeList, S.PlanOutcomeListOut>>;
export type _M4_DataSourceMetric = Nessuno<SoloNelFrontend<M4.DataSourceMetric, S.DataSourceMetricOut>>;
export type _M4_SchedulerJobStat = Nessuno<SoloNelFrontend<M4.SchedulerJobStat, S.SchedulerJobStatOut>>;
export type _M4_RecentScan = Nessuno<SoloNelFrontend<M4.RecentScan, S.RecentScanOut>>;
export type _M4_CacheKindStat = Nessuno<SoloNelFrontend<M4.CacheKindStat, S.CacheKindStatOut>>;
export type _M4_GapSuggestion = Nessuno<SoloNelFrontend<M4.GapSuggestion, S.GapSuggestionOut>>;
export type _M4_DataHealth = Nessuno<SoloNelFrontend<M4.DataHealth, S.DataHealthOut>>;
export type _M4_DeployHealth = Nessuno<SoloNelFrontend<M4.DeployHealth, S.DeployHealthOut>>;
export type _M4_Arretrato = Nessuno<SoloNelFrontend<M4.Arretrato, S.ArretratoOut>>;
export type _M4_Verification = Nessuno<SoloNelFrontend<M4.Verification, S.VerificationOut>>;
export type _M4_UsoRotta = Nessuno<SoloNelFrontend<M4.UsoRotta, S.UsoRottaOut>>;
export type _M4_UsoPagine = Nessuno<SoloNelFrontend<M4.UsoPagine, S.UsoPagineOut>>;
export type _M4_PlatformHealth = Nessuno<SoloNelFrontend<M4.PlatformHealth, S.PlatformHealthOut>>;
export type _M4_LogRecord = Nessuno<SoloNelFrontend<M4.LogRecord, S.LogRecordOut>>;
export type _M4_InfraLogSource = Nessuno<SoloNelFrontend<M4.InfraLogSource, S.InfraLogSourceOut>>;
export type _M4_InfraLogs = Nessuno<SoloNelFrontend<M4.InfraLogs, S.InfraLogsOut>>;
export type _M4_SignalDriftRow = Nessuno<SoloNelFrontend<M4.SignalDriftRow, S.SignalDriftRowOut>>;
export type _M4_DetectorPerfCell = Nessuno<SoloNelFrontend<M4.DetectorPerfCell, S.DetectorPerfCellOut>>;
export type _M4_DetectorPerfRow = Nessuno<SoloNelFrontend<M4.DetectorPerfRow, S.DetectorPerfRowOut>>;
export type _M4_DetectorPerfMeta = Nessuno<SoloNelFrontend<M4.DetectorPerfMeta, S.DetectorPerfMetaOut>>;
export type _M4_DetectorPerformance = Nessuno<SoloNelFrontend<M4.DetectorPerformance, S.DetectorPerformanceOut>>;
export type _M4_PlanCoverage = Nessuno<SoloNelFrontend<M4.PlanCoverage, S.PlanCoverageOut>>;
export type _M4_PlanPerfMeta = Nessuno<SoloNelFrontend<M4.PlanPerfMeta, S.PlanPerfMetaOut>>;
export type _M4_PlanPerfRow = Nessuno<SoloNelFrontend<M4.PlanPerfRow, S.PlanPerfRowOut>>;
export type _M4_PlanPerformance = Nessuno<SoloNelFrontend<M4.PlanPerformance, S.PlanPerformanceOut>>;
export type _M4_InfraComponent = Nessuno<SoloNelFrontend<M4.InfraComponent, S.InfraComponentOut>>;
export type _M4_TargetDown = Nessuno<SoloNelFrontend<M4.TargetDown, S.TargetDownOut>>;
export type _M4_AlertFiring = Nessuno<SoloNelFrontend<M4.AlertFiring, S.AlertFiringOut>>;
export type _M4_RestartDetail = Nessuno<SoloNelFrontend<M4.RestartDetail, S.RestartDetailOut>>;
export type _M4_InfraHealth = Nessuno<SoloNelFrontend<M4.InfraHealth, S.InfraHealthOut>>;
export type _M4_DegradedSource = Nessuno<SoloNelFrontend<M4.DegradedSource, S.DegradedSourceOut>>;
export type _M5_Preferito = Nessuno<SoloNelFrontend<M5.Preferito, S.PreferitoOut>>;
export type _M6_Stock = Nessuno<SoloNelFrontend<M6.Stock, S.StockOut>>;
export type _M6_StockSearchItem = Nessuno<SoloNelFrontend<M6.StockSearchItem, S.StockSearchItemOut>>;
export type _M6_StockSearch = Nessuno<SoloNelFrontend<M6.StockSearch, S.StockSearchOut>>;
export type _M6_IndexOption = Nessuno<SoloNelFrontend<M6.IndexOption, S.IndexOptionOut>>;
export type _M6_FilterOptions = Nessuno<SoloNelFrontend<M6.FilterOptions, S.FilterOptionsOut>>;
export type _M6_IndexStatus = Nessuno<SoloNelFrontend<M6.IndexStatus, S.IndexStatusOut>>;
export type _M6_CatalogStatus = Nessuno<SoloNelFrontend<M6.CatalogStatus, S.CatalogStatusOut>>;
export type _M6_AlertPeer = Nessuno<SoloNelFrontend<M6.AlertPeer, S.AlertPeerOut>>;
export type _M6_PlanBrief = Nessuno<SoloNelFrontend<M6.PlanBrief, S.PlanBriefOut>>;
export type _M6_Alert = Nessuno<SoloNelFrontend<M6.Alert, S.AlertOut>>;
export type _M6_AlertList = Nessuno<SoloNelFrontend<M6.AlertList, S.AlertListOut>>;
export type _M6_DigestResult = Nessuno<SoloNelFrontend<M6.DigestResult, S.DigestResultOut>>;
export type _M6_ScanStatusInfo = Nessuno<SoloNelFrontend<M6.ScanStatusInfo, S.ScanStatusOut>>;
export type _M6_KpiSummary = Nessuno<SoloNelFrontend<M6.KpiSummary, S.KpiSummaryOut>>;
export type _M6_AlertsByDayPoint = Nessuno<SoloNelFrontend<M6.AlertsByDayPoint, S.AlertsByDayPointOut>>;
export type _M6_TopStock = Nessuno<SoloNelFrontend<M6.TopStock, S.TopStockOut>>;
export type _M6_AlertsByIndexPoint = Nessuno<SoloNelFrontend<M6.AlertsByIndexPoint, S.AlertsByIndexPointOut>>;
export type _M6_SystemStatus = Nessuno<SoloNelFrontend<M6.SystemStatus, S.SystemStatusOut>>;
export type _M6_DashboardSummary = Nessuno<SoloNelFrontend<M6.DashboardSummary, S.DashboardSummaryOut>>;
export type _M6_MarketGlobal = Nessuno<SoloNelFrontend<M6.MarketGlobal, S.MarketGlobalOut>>;
export type _M6_IndexBreadth = Nessuno<SoloNelFrontend<M6.IndexBreadth, S.IndexBreadthOut>>;
export type _M6_IndexMover = Nessuno<SoloNelFrontend<M6.IndexMover, S.IndexMoverOut>>;
export type _M6_RsiDistribution = Nessuno<SoloNelFrontend<M6.RsiDistribution, S.RsiDistributionOut>>;
export type _M6_SectorBreadth = Nessuno<SoloNelFrontend<M6.SectorBreadth, S.SectorBreadthOut>>;
export type _M6_Mover = Nessuno<Exclude<SoloNelFrontend<M6.Mover, S.MoverOut>, "vol_as_of">>;
export type _M6_VolumeSpike = Nessuno<Exclude<SoloNelFrontend<M6.VolumeSpike, S.VolumeSpikeOut>, "vol_as_of">>;
export type _M6_TopVolume = Nessuno<Exclude<SoloNelFrontend<M6.TopVolume, S.TopVolumeOut>, "vol_as_of">>;
export type _M6_MoversBlock = Nessuno<SoloNelFrontend<M6.MoversBlock, S.MoversBlockOut>>;
export type _M6_TreemapLeaf = Nessuno<SoloNelFrontend<M6.TreemapLeaf, S.TreemapLeafOut>>;
export type _M6_MarketSummary = Nessuno<SoloNelFrontend<M6.MarketSummary, S.MarketSummaryOut>>;
export type _M6_IndicatorPeriods = Nessuno<SoloNelFrontend<M6.IndicatorPeriods, S.IndicatorPeriodsOut>>;
export type _M6_IndicatorSeries = Nessuno<SoloNelFrontend<M6.IndicatorSeries, S.IndicatorSeriesOut>>;
export type _M6_StockKpis = Nessuno<SoloNelFrontend<M6.StockKpis, S.StockKpisOut>>;
export type _M6_EffectiveRule = Nessuno<SoloNelFrontend<M6.EffectiveRule, S.EffectiveRuleOut>>;
export type _M6_StockDetail = Nessuno<SoloNelFrontend<M6.StockDetail, S.StockDetailOut>>;
export type _M6_StockNewsItem = Nessuno<SoloNelFrontend<M6.StockNewsItem, S.StockNewsItemOut>>;
export type _M6_StockNews = Nessuno<SoloNelFrontend<M6.StockNews, S.StockNewsOut>>;
export type _M6_PriceAlert = Nessuno<SoloNelFrontend<M6.PriceAlert, S.PriceAlertOut>>;
export type _M6_PriceAlertCreate = Nessuno<SoloNelFrontend<M6.PriceAlertCreate, S.PriceAlertCreate>>;
export type _M6_PriceAlertUpdate = Nessuno<SoloNelFrontend<M6.PriceAlertUpdate, S.PriceAlertUpdate>>;
export type _M6_Position = Nessuno<SoloNelFrontend<M6.Position, S.PositionOut>>;
export type _M6_PositionCreate = Nessuno<SoloNelFrontend<M6.PositionCreate, S.PositionCreate>>;
export type _M6_PositionUpdate = Nessuno<SoloNelFrontend<M6.PositionUpdate, S.PositionUpdate>>;
export type _M6_SpotlightCard = Nessuno<SoloNelFrontend<M6.SpotlightCard, S.SpotlightCardOut>>;
export type _M6_FundamentalsAnnual = Nessuno<SoloNelFrontend<M6.FundamentalsAnnual, S.FundamentalsAnnualOut>>;
export type _M6_FundamentalsQuarterly = Nessuno<SoloNelFrontend<M6.FundamentalsQuarterly, S.FundamentalsQuarterlyOut>>;
export type _M6_FundamentalsEarnings = Nessuno<SoloNelFrontend<M6.FundamentalsEarnings, S.FundamentalsEarningsOut>>;
export type _M6_MicroData = Nessuno<SoloNelFrontend<M6.MicroData, S.MicroDataOut>>;
export type _M6_InsiderTransaction = Nessuno<SoloNelFrontend<M6.InsiderTransaction, S.InsiderTransactionOut>>;
export type _M6_AnalystRating = Nessuno<SoloNelFrontend<M6.AnalystRating, S.AnalystRatingOut>>;
export type _M6_AnalystPriceTarget = Nessuno<SoloNelFrontend<M6.AnalystPriceTarget, S.AnalystPriceTargetOut>>;
export type _M6_CompanyProfile = Nessuno<SoloNelFrontend<M6.CompanyProfile, S.CompanyProfileOut>>;
export type _M6_Fundamentals = Nessuno<SoloNelFrontend<M6.Fundamentals, S.FundamentalsOut>>;
export type _M6_EtfHolding = Nessuno<SoloNelFrontend<M6.EtfHolding, S.EtfHoldingOut>>;
export type _M6_EtfHoldings = Nessuno<SoloNelFrontend<M6.EtfHoldings, S.EtfHoldingsOut>>;
export type _M6_SubScores = Nessuno<SoloNelFrontend<M6.SubScores, S.SubScoresOut>>;
export type _M6_StockScore = Nessuno<SoloNelFrontend<M6.StockScore, S.StockScoreOut>>;
export type _M6_TopPickItem = Nessuno<SoloNelFrontend<M6.TopPickItem, S.TopPickItemOut>>;
export type _M6_TopPicks = Nessuno<SoloNelFrontend<M6.TopPicks, S.TopPicksOut>>;
export type _M6_ScoreHistoryPoint = Nessuno<SoloNelFrontend<M6.ScoreHistoryPoint, S.ScoreHistoryPoint>>;
export type _M6_ScoreHistoryOut = Nessuno<SoloNelFrontend<M6.ScoreHistoryOut, S.ScoreHistoryOut>>;
export type _M6_EarningsEvent = Nessuno<SoloNelFrontend<M6.EarningsEvent, S.EarningsEventOut>>;
export type _M6_MacroEvent = Nessuno<SoloNelFrontend<M6.MacroEvent, S.MacroEventOut>>;
export type _M6_MacroRelease = Nessuno<SoloNelFrontend<M6.MacroRelease, S.MacroReleaseOut>>;
export type _M6_MacroSeriesDetail = Nessuno<SoloNelFrontend<M6.MacroSeriesDetail, S.MacroSeriesDetailOut>>;
export type _M6_Calendar = Nessuno<SoloNelFrontend<M6.Calendar, S.CalendarOut>>;
export type _M6_InstitutionalSummary = Nessuno<SoloNelFrontend<M6.InstitutionalSummary, S.InstitutionalSummaryOut>>;
export type _M6_HoldingDetail = Nessuno<SoloNelFrontend<M6.HoldingDetail, S.HoldingDetailOut>>;
export type _M6_InstitutionalDetail = Nessuno<SoloNelFrontend<M6.InstitutionalDetail, S.InstitutionalDetailOut>>;
export type _M6_TickerAggregate = Nessuno<SoloNelFrontend<M6.TickerAggregate, S.TickerAggregateOut>>;
export type _M6_ActionAggregate = Nessuno<SoloNelFrontend<M6.ActionAggregate, S.ActionAggregateOut>>;
export type _M6_AggregateStats = Nessuno<SoloNelFrontend<M6.AggregateStats, S.AggregateStatsOut>>;
export type _M6_TickerHolder = Nessuno<SoloNelFrontend<M6.TickerHolder, S.TickerHolderOut>>;
export type _M6_TickerHolders = Nessuno<SoloNelFrontend<M6.TickerHolders, S.TickerHoldersOut>>;
export type _M7_IndexStatus = Nessuno<SoloNelFrontend<M7.IndexStatus, S.IndexStatusOut>>;
export type _M7_CatalogStatus = Nessuno<SoloNelFrontend<M7.CatalogStatus, S.CatalogStatusOut>>;
export type _M8_EquityPoint = Nessuno<SoloNelFrontend<M8.EquityPoint, S.EquityPointOut>>;
export type _M8_EquityCurve = Nessuno<SoloNelFrontend<M8.EquityCurve, S.EquityCurveOut>>;
export type _M9_LiveAsset = Nessuno<SoloNelFrontend<M9.LiveAsset, S.LiveAsset>>;
export type _M10_LiveMover = Nessuno<SoloNelFrontend<M10.LiveMover, S.LiveMoverOut>>;
export type _M11_MarketDetail = Nessuno<SoloNelFrontend<M11.MarketDetail, S.MarketDetailOut>>;
export type _M12_TimeframeKpis = Nessuno<SoloNelFrontend<M12.TimeframeKpis, S.TimeframeKpisOut>>;
export type _M12_MultiTfKpis = Nessuno<SoloNelFrontend<M12.MultiTfKpis, S.MultiTfKpisOut>>;
export type _M13_CalibrationBucket = Nessuno<SoloNelFrontend<M13.CalibrationBucket, S.CalibrationBucketOut>>;
export type _M13_Calibration = Nessuno<SoloNelFrontend<M13.Calibration, S.CalibrationOut>>;
export type _M14_PhaseTiming = Nessuno<SoloNelFrontend<M14.PhaseTiming, S.PhaseTimingOut>>;
export type _M14_ScanRunSummary = Nessuno<SoloNelFrontend<M14.ScanRunSummary, S.ScanRunSummaryOut>>;
export type _M15_SectorStockRow = Nessuno<SoloNelFrontend<M15.SectorStockRow, S.SectorStockRow>>;
export type _M15_CountBucket = Nessuno<SoloNelFrontend<M15.CountBucket, S.CountBucket>>;
export type _M15_PillarAverages = Nessuno<SoloNelFrontend<M15.PillarAverages, S.PillarAverages>>;
export type _M15_SectorKpis = Nessuno<SoloNelFrontend<M15.SectorKpis, S.SectorKpis>>;
export type _M15_SectorDetail = Nessuno<SoloNelFrontend<M15.SectorDetail, S.SectorDetailOut>>;
export type _M15_SectorTrendPoint = Nessuno<SoloNelFrontend<M15.SectorTrendPoint, S.SectorTrendPoint>>;
export type _M15_SectorSummary = Nessuno<SoloNelFrontend<M15.SectorSummary, S.SectorSummary>>;
export type _M15_IndustryRow = Nessuno<SoloNelFrontend<M15.IndustryRow, S.IndustryRow>>;
export type _M15_SectorsOverview = Nessuno<SoloNelFrontend<M15.SectorsOverview, S.SectorsOverviewOut>>;
export type _M15_LeaderRow = Nessuno<SoloNelFrontend<M15.LeaderRow, S.LeaderRowOut>>;
export type _M15_Leaderboards = Nessuno<SoloNelFrontend<M15.Leaderboards, S.LeaderboardsOut>>;
export type _M16_Setup = Nessuno<SoloNelFrontend<M16.Setup, S.SetupOut>>;
