/* GENERATO da backend/app/scripts/genera_tipi_frontend.py — non modificare.
 *
 * Per ogni tipo scritto a mano che ha un modello del server, `tsc` pretende
 * che il tipo NON dichiari campi che il server non manda (FA-111). Le
 * eccezioni, ognuna con la sua ragione, stanno nello script. */
import type * as S from "./schema.gen";
import type * as M0 from "@/api/alerts";
import type * as M1 from "@/api/cruscotto";
import type * as M2 from "@/api/dashboard";
import type * as M3 from "@/api/drawings";
import type * as M4 from "@/api/planOutcomes";
import type * as M5 from "@/api/platformHealth";
import type * as M6 from "@/api/preferiti";
import type * as M7 from "@/api/types";
import type * as M8 from "@/hooks/useCatalogStatus";
import type * as M9 from "@/hooks/useEquityCurve";
import type * as M10 from "@/hooks/useLiveAssets";
import type * as M11 from "@/hooks/useLiveUniverseMovers";
import type * as M12 from "@/hooks/useMarketDetail";
import type * as M13 from "@/hooks/useMultiTfKpis";
import type * as M14 from "@/hooks/useRulePerformance";
import type * as M15 from "@/hooks/useScanLog";
import type * as M16 from "@/hooks/useSectorDetail";
import type * as M17 from "@/hooks/useSetups";

type SoloNelFrontend<F, S> = Exclude<keyof F, keyof S>;
type Nessuno<T extends never> = T;

export type _M0_ConfluenceComponent = Nessuno<SoloNelFrontend<M0.ConfluenceComponent, S.ConfluenceComponentOut>>;
export type _M0_Confluence = Nessuno<SoloNelFrontend<M0.Confluence, S.ConfluenceOut>>;
export type _M1_NovitaTitolo = Nessuno<SoloNelFrontend<M1.NovitaTitolo, S.NovitaTitoloOut>>;
export type _M1_DallUltimaVisita = Nessuno<SoloNelFrontend<M1.DallUltimaVisita, S.DallUltimaVisitaOut>>;
export type _M2_PremarketMover = Nessuno<SoloNelFrontend<M2.PremarketMover, S.PremarketMoverOut>>;
export type _M2_PremarketMovers = Nessuno<SoloNelFrontend<M2.PremarketMovers, S.PremarketMoversOut>>;
export type _M3_StockDrawings = Nessuno<SoloNelFrontend<M3.StockDrawings, S.StockDrawingsOut>>;
export type _M4_PlanOutcomeRow = Nessuno<SoloNelFrontend<M4.PlanOutcomeRow, S.PlanOutcomeRowOut>>;
export type _M4_PlanOutcomeSummary = Nessuno<SoloNelFrontend<M4.PlanOutcomeSummary, S.PlanOutcomeSummaryOut>>;
export type _M4_PlanOutcomeList = Nessuno<SoloNelFrontend<M4.PlanOutcomeList, S.PlanOutcomeListOut>>;
export type _M5_DataSourceMetric = Nessuno<SoloNelFrontend<M5.DataSourceMetric, S.DataSourceMetricOut>>;
export type _M5_SchedulerJobStat = Nessuno<SoloNelFrontend<M5.SchedulerJobStat, S.SchedulerJobStatOut>>;
export type _M5_RecentScan = Nessuno<SoloNelFrontend<M5.RecentScan, S.RecentScanOut>>;
export type _M5_CacheKindStat = Nessuno<SoloNelFrontend<M5.CacheKindStat, S.CacheKindStatOut>>;
export type _M5_GapSuggestion = Nessuno<SoloNelFrontend<M5.GapSuggestion, S.GapSuggestionOut>>;
export type _M5_DataHealth = Nessuno<SoloNelFrontend<M5.DataHealth, S.DataHealthOut>>;
export type _M5_DeployHealth = Nessuno<SoloNelFrontend<M5.DeployHealth, S.DeployHealthOut>>;
export type _M5_Arretrato = Nessuno<SoloNelFrontend<M5.Arretrato, S.ArretratoOut>>;
export type _M5_Verification = Nessuno<SoloNelFrontend<M5.Verification, S.VerificationOut>>;
export type _M5_UsoRotta = Nessuno<SoloNelFrontend<M5.UsoRotta, S.UsoRottaOut>>;
export type _M5_UsoPagine = Nessuno<SoloNelFrontend<M5.UsoPagine, S.UsoPagineOut>>;
export type _M5_PlatformHealth = Nessuno<SoloNelFrontend<M5.PlatformHealth, S.PlatformHealthOut>>;
export type _M5_LogRecord = Nessuno<SoloNelFrontend<M5.LogRecord, S.LogRecordOut>>;
export type _M5_InfraLogSource = Nessuno<SoloNelFrontend<M5.InfraLogSource, S.InfraLogSourceOut>>;
export type _M5_InfraLogs = Nessuno<SoloNelFrontend<M5.InfraLogs, S.InfraLogsOut>>;
export type _M5_SignalDriftRow = Nessuno<SoloNelFrontend<M5.SignalDriftRow, S.SignalDriftRowOut>>;
export type _M5_DetectorPerfCell = Nessuno<SoloNelFrontend<M5.DetectorPerfCell, S.DetectorPerfCellOut>>;
export type _M5_DetectorPerfRow = Nessuno<SoloNelFrontend<M5.DetectorPerfRow, S.DetectorPerfRowOut>>;
export type _M5_DetectorPerfMeta = Nessuno<SoloNelFrontend<M5.DetectorPerfMeta, S.DetectorPerfMetaOut>>;
export type _M5_DetectorPerformance = Nessuno<SoloNelFrontend<M5.DetectorPerformance, S.DetectorPerformanceOut>>;
export type _M5_PlanCoverage = Nessuno<SoloNelFrontend<M5.PlanCoverage, S.PlanCoverageOut>>;
export type _M5_PlanPerfMeta = Nessuno<SoloNelFrontend<M5.PlanPerfMeta, S.PlanPerfMetaOut>>;
export type _M5_PlanPerfRow = Nessuno<SoloNelFrontend<M5.PlanPerfRow, S.PlanPerfRowOut>>;
export type _M5_PlanPerformance = Nessuno<SoloNelFrontend<M5.PlanPerformance, S.PlanPerformanceOut>>;
export type _M5_InfraComponent = Nessuno<SoloNelFrontend<M5.InfraComponent, S.InfraComponentOut>>;
export type _M5_TargetDown = Nessuno<SoloNelFrontend<M5.TargetDown, S.TargetDownOut>>;
export type _M5_AlertFiring = Nessuno<SoloNelFrontend<M5.AlertFiring, S.AlertFiringOut>>;
export type _M5_RestartDetail = Nessuno<SoloNelFrontend<M5.RestartDetail, S.RestartDetailOut>>;
export type _M5_InfraHealth = Nessuno<SoloNelFrontend<M5.InfraHealth, S.InfraHealthOut>>;
export type _M5_DegradedSource = Nessuno<SoloNelFrontend<M5.DegradedSource, S.DegradedSourceOut>>;
export type _M6_Preferito = Nessuno<SoloNelFrontend<M6.Preferito, S.PreferitoOut>>;
export type _M7_Stock = Nessuno<SoloNelFrontend<M7.Stock, S.StockOut>>;
export type _M7_StockSearchItem = Nessuno<SoloNelFrontend<M7.StockSearchItem, S.StockSearchItemOut>>;
export type _M7_StockSearch = Nessuno<SoloNelFrontend<M7.StockSearch, S.StockSearchOut>>;
export type _M7_IndexOption = Nessuno<SoloNelFrontend<M7.IndexOption, S.IndexOptionOut>>;
export type _M7_FilterOptions = Nessuno<SoloNelFrontend<M7.FilterOptions, S.FilterOptionsOut>>;
export type _M7_IndexStatus = Nessuno<SoloNelFrontend<M7.IndexStatus, S.IndexStatusOut>>;
export type _M7_CatalogStatus = Nessuno<SoloNelFrontend<M7.CatalogStatus, S.CatalogStatusOut>>;
export type _M7_AlertPeer = Nessuno<SoloNelFrontend<M7.AlertPeer, S.AlertPeerOut>>;
export type _M7_PlanBrief = Nessuno<SoloNelFrontend<M7.PlanBrief, S.PlanBriefOut>>;
export type _M7_Alert = Nessuno<SoloNelFrontend<M7.Alert, S.AlertOut>>;
export type _M7_AlertList = Nessuno<SoloNelFrontend<M7.AlertList, S.AlertListOut>>;
export type _M7_DigestResult = Nessuno<SoloNelFrontend<M7.DigestResult, S.DigestResultOut>>;
export type _M7_ScanStatusInfo = Nessuno<SoloNelFrontend<M7.ScanStatusInfo, S.ScanStatusOut>>;
export type _M7_KpiSummary = Nessuno<SoloNelFrontend<M7.KpiSummary, S.KpiSummaryOut>>;
export type _M7_AlertsByDayPoint = Nessuno<SoloNelFrontend<M7.AlertsByDayPoint, S.AlertsByDayPointOut>>;
export type _M7_TopStock = Nessuno<SoloNelFrontend<M7.TopStock, S.TopStockOut>>;
export type _M7_AlertsByIndexPoint = Nessuno<SoloNelFrontend<M7.AlertsByIndexPoint, S.AlertsByIndexPointOut>>;
export type _M7_SystemStatus = Nessuno<SoloNelFrontend<M7.SystemStatus, S.SystemStatusOut>>;
export type _M7_DashboardSummary = Nessuno<SoloNelFrontend<M7.DashboardSummary, S.DashboardSummaryOut>>;
export type _M7_MarketGlobal = Nessuno<SoloNelFrontend<M7.MarketGlobal, S.MarketGlobalOut>>;
export type _M7_IndexBreadth = Nessuno<SoloNelFrontend<M7.IndexBreadth, S.IndexBreadthOut>>;
export type _M7_IndexMover = Nessuno<SoloNelFrontend<M7.IndexMover, S.IndexMoverOut>>;
export type _M7_RsiDistribution = Nessuno<SoloNelFrontend<M7.RsiDistribution, S.RsiDistributionOut>>;
export type _M7_SectorBreadth = Nessuno<SoloNelFrontend<M7.SectorBreadth, S.SectorBreadthOut>>;
export type _M7_Mover = Nessuno<Exclude<SoloNelFrontend<M7.Mover, S.MoverOut>, "vol_as_of">>;
export type _M7_VolumeSpike = Nessuno<Exclude<SoloNelFrontend<M7.VolumeSpike, S.VolumeSpikeOut>, "vol_as_of">>;
export type _M7_TopVolume = Nessuno<Exclude<SoloNelFrontend<M7.TopVolume, S.TopVolumeOut>, "vol_as_of">>;
export type _M7_MoversBlock = Nessuno<SoloNelFrontend<M7.MoversBlock, S.MoversBlockOut>>;
export type _M7_TreemapLeaf = Nessuno<SoloNelFrontend<M7.TreemapLeaf, S.TreemapLeafOut>>;
export type _M7_MarketSummary = Nessuno<SoloNelFrontend<M7.MarketSummary, S.MarketSummaryOut>>;
export type _M7_IndicatorPeriods = Nessuno<SoloNelFrontend<M7.IndicatorPeriods, S.IndicatorPeriodsOut>>;
export type _M7_IndicatorSeries = Nessuno<SoloNelFrontend<M7.IndicatorSeries, S.IndicatorSeriesOut>>;
export type _M7_StockKpis = Nessuno<SoloNelFrontend<M7.StockKpis, S.StockKpisOut>>;
export type _M7_EffectiveRule = Nessuno<SoloNelFrontend<M7.EffectiveRule, S.EffectiveRuleOut>>;
export type _M7_StockDetail = Nessuno<SoloNelFrontend<M7.StockDetail, S.StockDetailOut>>;
export type _M7_StockNewsItem = Nessuno<SoloNelFrontend<M7.StockNewsItem, S.StockNewsItemOut>>;
export type _M7_StockNews = Nessuno<SoloNelFrontend<M7.StockNews, S.StockNewsOut>>;
export type _M7_PriceAlert = Nessuno<SoloNelFrontend<M7.PriceAlert, S.PriceAlertOut>>;
export type _M7_PriceAlertCreate = Nessuno<SoloNelFrontend<M7.PriceAlertCreate, S.PriceAlertCreate>>;
export type _M7_PriceAlertUpdate = Nessuno<SoloNelFrontend<M7.PriceAlertUpdate, S.PriceAlertUpdate>>;
export type _M7_Position = Nessuno<SoloNelFrontend<M7.Position, S.PositionOut>>;
export type _M7_PositionCreate = Nessuno<SoloNelFrontend<M7.PositionCreate, S.PositionCreate>>;
export type _M7_PositionUpdate = Nessuno<SoloNelFrontend<M7.PositionUpdate, S.PositionUpdate>>;
export type _M7_SpotlightCard = Nessuno<SoloNelFrontend<M7.SpotlightCard, S.SpotlightCardOut>>;
export type _M7_FundamentalsAnnual = Nessuno<SoloNelFrontend<M7.FundamentalsAnnual, S.FundamentalsAnnualOut>>;
export type _M7_FundamentalsQuarterly = Nessuno<SoloNelFrontend<M7.FundamentalsQuarterly, S.FundamentalsQuarterlyOut>>;
export type _M7_FundamentalsEarnings = Nessuno<SoloNelFrontend<M7.FundamentalsEarnings, S.FundamentalsEarningsOut>>;
export type _M7_MicroData = Nessuno<SoloNelFrontend<M7.MicroData, S.MicroDataOut>>;
export type _M7_InsiderTransaction = Nessuno<SoloNelFrontend<M7.InsiderTransaction, S.InsiderTransactionOut>>;
export type _M7_AnalystRating = Nessuno<SoloNelFrontend<M7.AnalystRating, S.AnalystRatingOut>>;
export type _M7_AnalystPriceTarget = Nessuno<SoloNelFrontend<M7.AnalystPriceTarget, S.AnalystPriceTargetOut>>;
export type _M7_CompanyProfile = Nessuno<SoloNelFrontend<M7.CompanyProfile, S.CompanyProfileOut>>;
export type _M7_Fundamentals = Nessuno<SoloNelFrontend<M7.Fundamentals, S.FundamentalsOut>>;
export type _M7_EtfHolding = Nessuno<SoloNelFrontend<M7.EtfHolding, S.EtfHoldingOut>>;
export type _M7_EtfHoldings = Nessuno<SoloNelFrontend<M7.EtfHoldings, S.EtfHoldingsOut>>;
export type _M7_SubScores = Nessuno<SoloNelFrontend<M7.SubScores, S.SubScoresOut>>;
export type _M7_StockScore = Nessuno<SoloNelFrontend<M7.StockScore, S.StockScoreOut>>;
export type _M7_TopPickItem = Nessuno<SoloNelFrontend<M7.TopPickItem, S.TopPickItemOut>>;
export type _M7_TopPicks = Nessuno<SoloNelFrontend<M7.TopPicks, S.TopPicksOut>>;
export type _M7_ScoreHistoryPoint = Nessuno<SoloNelFrontend<M7.ScoreHistoryPoint, S.ScoreHistoryPoint>>;
export type _M7_ScoreHistoryOut = Nessuno<SoloNelFrontend<M7.ScoreHistoryOut, S.ScoreHistoryOut>>;
export type _M7_EarningsEvent = Nessuno<SoloNelFrontend<M7.EarningsEvent, S.EarningsEventOut>>;
export type _M7_MacroEvent = Nessuno<SoloNelFrontend<M7.MacroEvent, S.MacroEventOut>>;
export type _M7_MacroRelease = Nessuno<SoloNelFrontend<M7.MacroRelease, S.MacroReleaseOut>>;
export type _M7_MacroSeriesDetail = Nessuno<SoloNelFrontend<M7.MacroSeriesDetail, S.MacroSeriesDetailOut>>;
export type _M7_Calendar = Nessuno<SoloNelFrontend<M7.Calendar, S.CalendarOut>>;
export type _M7_InstitutionalSummary = Nessuno<SoloNelFrontend<M7.InstitutionalSummary, S.InstitutionalSummaryOut>>;
export type _M7_HoldingDetail = Nessuno<SoloNelFrontend<M7.HoldingDetail, S.HoldingDetailOut>>;
export type _M7_InstitutionalDetail = Nessuno<SoloNelFrontend<M7.InstitutionalDetail, S.InstitutionalDetailOut>>;
export type _M7_TickerAggregate = Nessuno<SoloNelFrontend<M7.TickerAggregate, S.TickerAggregateOut>>;
export type _M7_ActionAggregate = Nessuno<SoloNelFrontend<M7.ActionAggregate, S.ActionAggregateOut>>;
export type _M7_AggregateStats = Nessuno<SoloNelFrontend<M7.AggregateStats, S.AggregateStatsOut>>;
export type _M7_TickerHolder = Nessuno<SoloNelFrontend<M7.TickerHolder, S.TickerHolderOut>>;
export type _M7_TickerHolders = Nessuno<SoloNelFrontend<M7.TickerHolders, S.TickerHoldersOut>>;
export type _M8_IndexStatus = Nessuno<SoloNelFrontend<M8.IndexStatus, S.IndexStatusOut>>;
export type _M8_CatalogStatus = Nessuno<SoloNelFrontend<M8.CatalogStatus, S.CatalogStatusOut>>;
export type _M9_EquityPoint = Nessuno<SoloNelFrontend<M9.EquityPoint, S.EquityPointOut>>;
export type _M9_EquityCurve = Nessuno<SoloNelFrontend<M9.EquityCurve, S.EquityCurveOut>>;
export type _M10_LiveAsset = Nessuno<SoloNelFrontend<M10.LiveAsset, S.LiveAsset>>;
export type _M11_LiveMover = Nessuno<SoloNelFrontend<M11.LiveMover, S.LiveMoverOut>>;
export type _M12_MarketDetail = Nessuno<SoloNelFrontend<M12.MarketDetail, S.MarketDetailOut>>;
export type _M13_TimeframeKpis = Nessuno<SoloNelFrontend<M13.TimeframeKpis, S.TimeframeKpisOut>>;
export type _M13_MultiTfKpis = Nessuno<SoloNelFrontend<M13.MultiTfKpis, S.MultiTfKpisOut>>;
export type _M14_CalibrationBucket = Nessuno<SoloNelFrontend<M14.CalibrationBucket, S.CalibrationBucketOut>>;
export type _M14_Calibration = Nessuno<SoloNelFrontend<M14.Calibration, S.CalibrationOut>>;
export type _M15_PhaseTiming = Nessuno<SoloNelFrontend<M15.PhaseTiming, S.PhaseTimingOut>>;
export type _M15_ScanRunSummary = Nessuno<SoloNelFrontend<M15.ScanRunSummary, S.ScanRunSummaryOut>>;
export type _M16_SectorStockRow = Nessuno<SoloNelFrontend<M16.SectorStockRow, S.SectorStockRow>>;
export type _M16_CountBucket = Nessuno<SoloNelFrontend<M16.CountBucket, S.CountBucket>>;
export type _M16_PillarAverages = Nessuno<SoloNelFrontend<M16.PillarAverages, S.PillarAverages>>;
export type _M16_SectorKpis = Nessuno<SoloNelFrontend<M16.SectorKpis, S.SectorKpis>>;
export type _M16_SectorDetail = Nessuno<SoloNelFrontend<M16.SectorDetail, S.SectorDetailOut>>;
export type _M16_SectorTrendPoint = Nessuno<SoloNelFrontend<M16.SectorTrendPoint, S.SectorTrendPoint>>;
export type _M16_SectorSummary = Nessuno<SoloNelFrontend<M16.SectorSummary, S.SectorSummary>>;
export type _M16_IndustryRow = Nessuno<SoloNelFrontend<M16.IndustryRow, S.IndustryRow>>;
export type _M16_SectorsOverview = Nessuno<SoloNelFrontend<M16.SectorsOverview, S.SectorsOverviewOut>>;
export type _M16_LeaderRow = Nessuno<SoloNelFrontend<M16.LeaderRow, S.LeaderRowOut>>;
export type _M16_Leaderboards = Nessuno<SoloNelFrontend<M16.Leaderboards, S.LeaderboardsOut>>;
export type _M17_Setup = Nessuno<SoloNelFrontend<M17.Setup, S.SetupOut>>;
