/* GENERATO da backend/app/scripts/genera_tipi_frontend.py — non modificare.
 *
 * Per ogni tipo scritto a mano che ha un modello del server, `tsc` pretende
 * che il tipo NON dichiari campi che il server non manda (FA-111). Le
 * eccezioni, ognuna con la sua ragione, stanno nello script. */
import type * as S from "./schema.gen";
import type * as M0 from "@/api/alerts";
import type * as M1 from "@/api/catalogo";
import type * as M2 from "@/api/cruscotto";
import type * as M3 from "@/api/dashboard";
import type * as M4 from "@/api/drawings";
import type * as M5 from "@/api/planOutcomes";
import type * as M6 from "@/api/platformHealth";
import type * as M7 from "@/api/preferiti";
import type * as M8 from "@/api/types";
import type * as M9 from "@/hooks/useCatalogStatus";
import type * as M10 from "@/hooks/useEquityCurve";
import type * as M11 from "@/hooks/useLiveAssets";
import type * as M12 from "@/hooks/useLiveUniverseMovers";
import type * as M13 from "@/hooks/useMarketDetail";
import type * as M14 from "@/hooks/useMultiTfKpis";
import type * as M15 from "@/hooks/useRulePerformance";
import type * as M16 from "@/hooks/useScanLog";
import type * as M17 from "@/hooks/useSectorDetail";
import type * as M18 from "@/hooks/useSetups";

type SoloNelFrontend<F, S> = Exclude<keyof F, keyof S>;
type Nessuno<T extends never> = T;

export type _M0_ConfluenceComponent = Nessuno<SoloNelFrontend<M0.ConfluenceComponent, S.ConfluenceComponentOut>>;
export type _M0_Confluence = Nessuno<SoloNelFrontend<M0.Confluence, S.ConfluenceOut>>;
export type _M1_Candidato = Nessuno<SoloNelFrontend<M1.Candidato, S.CandidatoOut>>;
export type _M1_VerificaFonte = Nessuno<SoloNelFrontend<M1.VerificaFonte, S.VerificaFonteOut>>;
export type _M2_NovitaTitolo = Nessuno<SoloNelFrontend<M2.NovitaTitolo, S.NovitaTitoloOut>>;
export type _M2_DallUltimaVisita = Nessuno<SoloNelFrontend<M2.DallUltimaVisita, S.DallUltimaVisitaOut>>;
export type _M3_PremarketMover = Nessuno<SoloNelFrontend<M3.PremarketMover, S.PremarketMoverOut>>;
export type _M3_PremarketMovers = Nessuno<SoloNelFrontend<M3.PremarketMovers, S.PremarketMoversOut>>;
export type _M4_StockDrawings = Nessuno<SoloNelFrontend<M4.StockDrawings, S.StockDrawingsOut>>;
export type _M5_PlanOutcomeRow = Nessuno<SoloNelFrontend<M5.PlanOutcomeRow, S.PlanOutcomeRowOut>>;
export type _M5_PlanOutcomeSummary = Nessuno<SoloNelFrontend<M5.PlanOutcomeSummary, S.PlanOutcomeSummaryOut>>;
export type _M5_PlanOutcomeList = Nessuno<SoloNelFrontend<M5.PlanOutcomeList, S.PlanOutcomeListOut>>;
export type _M6_DataSourceMetric = Nessuno<SoloNelFrontend<M6.DataSourceMetric, S.DataSourceMetricOut>>;
export type _M6_SchedulerJobStat = Nessuno<SoloNelFrontend<M6.SchedulerJobStat, S.SchedulerJobStatOut>>;
export type _M6_RecentScan = Nessuno<SoloNelFrontend<M6.RecentScan, S.RecentScanOut>>;
export type _M6_CacheKindStat = Nessuno<SoloNelFrontend<M6.CacheKindStat, S.CacheKindStatOut>>;
export type _M6_GapSuggestion = Nessuno<SoloNelFrontend<M6.GapSuggestion, S.GapSuggestionOut>>;
export type _M6_DataHealth = Nessuno<SoloNelFrontend<M6.DataHealth, S.DataHealthOut>>;
export type _M6_DeployHealth = Nessuno<SoloNelFrontend<M6.DeployHealth, S.DeployHealthOut>>;
export type _M6_Arretrato = Nessuno<SoloNelFrontend<M6.Arretrato, S.ArretratoOut>>;
export type _M6_Verification = Nessuno<SoloNelFrontend<M6.Verification, S.VerificationOut>>;
export type _M6_UsoRotta = Nessuno<SoloNelFrontend<M6.UsoRotta, S.UsoRottaOut>>;
export type _M6_UsoPagine = Nessuno<SoloNelFrontend<M6.UsoPagine, S.UsoPagineOut>>;
export type _M6_PlatformHealth = Nessuno<SoloNelFrontend<M6.PlatformHealth, S.PlatformHealthOut>>;
export type _M6_TitoloFermo = Nessuno<SoloNelFrontend<M6.TitoloFermo, S.TitoloFermoOut>>;
export type _M6_Catalogo = Nessuno<SoloNelFrontend<M6.Catalogo, S.CatalogoOut>>;
export type _M6_LogRecord = Nessuno<SoloNelFrontend<M6.LogRecord, S.LogRecordOut>>;
export type _M6_InfraLogSource = Nessuno<SoloNelFrontend<M6.InfraLogSource, S.InfraLogSourceOut>>;
export type _M6_InfraLogs = Nessuno<SoloNelFrontend<M6.InfraLogs, S.InfraLogsOut>>;
export type _M6_SignalDriftRow = Nessuno<SoloNelFrontend<M6.SignalDriftRow, S.SignalDriftRowOut>>;
export type _M6_DetectorPerfCell = Nessuno<SoloNelFrontend<M6.DetectorPerfCell, S.DetectorPerfCellOut>>;
export type _M6_DetectorPerfRow = Nessuno<SoloNelFrontend<M6.DetectorPerfRow, S.DetectorPerfRowOut>>;
export type _M6_DetectorPerfMeta = Nessuno<SoloNelFrontend<M6.DetectorPerfMeta, S.DetectorPerfMetaOut>>;
export type _M6_DetectorPerformance = Nessuno<SoloNelFrontend<M6.DetectorPerformance, S.DetectorPerformanceOut>>;
export type _M6_PlanCoverage = Nessuno<SoloNelFrontend<M6.PlanCoverage, S.PlanCoverageOut>>;
export type _M6_PlanPerfMeta = Nessuno<SoloNelFrontend<M6.PlanPerfMeta, S.PlanPerfMetaOut>>;
export type _M6_PlanPerfRow = Nessuno<SoloNelFrontend<M6.PlanPerfRow, S.PlanPerfRowOut>>;
export type _M6_PlanPerformance = Nessuno<SoloNelFrontend<M6.PlanPerformance, S.PlanPerformanceOut>>;
export type _M6_InfraComponent = Nessuno<SoloNelFrontend<M6.InfraComponent, S.InfraComponentOut>>;
export type _M6_TargetDown = Nessuno<SoloNelFrontend<M6.TargetDown, S.TargetDownOut>>;
export type _M6_AlertFiring = Nessuno<SoloNelFrontend<M6.AlertFiring, S.AlertFiringOut>>;
export type _M6_RestartDetail = Nessuno<SoloNelFrontend<M6.RestartDetail, S.RestartDetailOut>>;
export type _M6_InfraHealth = Nessuno<SoloNelFrontend<M6.InfraHealth, S.InfraHealthOut>>;
export type _M6_DegradedSource = Nessuno<SoloNelFrontend<M6.DegradedSource, S.DegradedSourceOut>>;
export type _M7_Preferito = Nessuno<SoloNelFrontend<M7.Preferito, S.PreferitoOut>>;
export type _M8_Stock = Nessuno<SoloNelFrontend<M8.Stock, S.StockOut>>;
export type _M8_StockSearchItem = Nessuno<SoloNelFrontend<M8.StockSearchItem, S.StockSearchItemOut>>;
export type _M8_StockSearch = Nessuno<SoloNelFrontend<M8.StockSearch, S.StockSearchOut>>;
export type _M8_IndexOption = Nessuno<SoloNelFrontend<M8.IndexOption, S.IndexOptionOut>>;
export type _M8_FilterOptions = Nessuno<SoloNelFrontend<M8.FilterOptions, S.FilterOptionsOut>>;
export type _M8_IndexStatus = Nessuno<SoloNelFrontend<M8.IndexStatus, S.IndexStatusOut>>;
export type _M8_CatalogStatus = Nessuno<SoloNelFrontend<M8.CatalogStatus, S.CatalogStatusOut>>;
export type _M8_AlertPeer = Nessuno<SoloNelFrontend<M8.AlertPeer, S.AlertPeerOut>>;
export type _M8_PlanBrief = Nessuno<SoloNelFrontend<M8.PlanBrief, S.PlanBriefOut>>;
export type _M8_Alert = Nessuno<SoloNelFrontend<M8.Alert, S.AlertOut>>;
export type _M8_AlertList = Nessuno<SoloNelFrontend<M8.AlertList, S.AlertListOut>>;
export type _M8_DigestResult = Nessuno<SoloNelFrontend<M8.DigestResult, S.DigestResultOut>>;
export type _M8_ScanStatusInfo = Nessuno<SoloNelFrontend<M8.ScanStatusInfo, S.ScanStatusOut>>;
export type _M8_KpiSummary = Nessuno<SoloNelFrontend<M8.KpiSummary, S.KpiSummaryOut>>;
export type _M8_AlertsByDayPoint = Nessuno<SoloNelFrontend<M8.AlertsByDayPoint, S.AlertsByDayPointOut>>;
export type _M8_TopStock = Nessuno<SoloNelFrontend<M8.TopStock, S.TopStockOut>>;
export type _M8_AlertsByIndexPoint = Nessuno<SoloNelFrontend<M8.AlertsByIndexPoint, S.AlertsByIndexPointOut>>;
export type _M8_SystemStatus = Nessuno<SoloNelFrontend<M8.SystemStatus, S.SystemStatusOut>>;
export type _M8_DashboardSummary = Nessuno<SoloNelFrontend<M8.DashboardSummary, S.DashboardSummaryOut>>;
export type _M8_MarketGlobal = Nessuno<SoloNelFrontend<M8.MarketGlobal, S.MarketGlobalOut>>;
export type _M8_IndexBreadth = Nessuno<SoloNelFrontend<M8.IndexBreadth, S.IndexBreadthOut>>;
export type _M8_IndexMover = Nessuno<SoloNelFrontend<M8.IndexMover, S.IndexMoverOut>>;
export type _M8_RsiDistribution = Nessuno<SoloNelFrontend<M8.RsiDistribution, S.RsiDistributionOut>>;
export type _M8_SectorBreadth = Nessuno<SoloNelFrontend<M8.SectorBreadth, S.SectorBreadthOut>>;
export type _M8_Mover = Nessuno<Exclude<SoloNelFrontend<M8.Mover, S.MoverOut>, "vol_as_of">>;
export type _M8_VolumeSpike = Nessuno<Exclude<SoloNelFrontend<M8.VolumeSpike, S.VolumeSpikeOut>, "vol_as_of">>;
export type _M8_TopVolume = Nessuno<Exclude<SoloNelFrontend<M8.TopVolume, S.TopVolumeOut>, "vol_as_of">>;
export type _M8_MoversBlock = Nessuno<SoloNelFrontend<M8.MoversBlock, S.MoversBlockOut>>;
export type _M8_TreemapLeaf = Nessuno<SoloNelFrontend<M8.TreemapLeaf, S.TreemapLeafOut>>;
export type _M8_MarketSummary = Nessuno<SoloNelFrontend<M8.MarketSummary, S.MarketSummaryOut>>;
export type _M8_IndicatorPeriods = Nessuno<SoloNelFrontend<M8.IndicatorPeriods, S.IndicatorPeriodsOut>>;
export type _M8_IndicatorSeries = Nessuno<SoloNelFrontend<M8.IndicatorSeries, S.IndicatorSeriesOut>>;
export type _M8_StockKpis = Nessuno<SoloNelFrontend<M8.StockKpis, S.StockKpisOut>>;
export type _M8_EffectiveRule = Nessuno<SoloNelFrontend<M8.EffectiveRule, S.EffectiveRuleOut>>;
export type _M8_StockDetail = Nessuno<SoloNelFrontend<M8.StockDetail, S.StockDetailOut>>;
export type _M8_StockNewsItem = Nessuno<SoloNelFrontend<M8.StockNewsItem, S.StockNewsItemOut>>;
export type _M8_StockNews = Nessuno<SoloNelFrontend<M8.StockNews, S.StockNewsOut>>;
export type _M8_PriceAlert = Nessuno<SoloNelFrontend<M8.PriceAlert, S.PriceAlertOut>>;
export type _M8_PriceAlertCreate = Nessuno<SoloNelFrontend<M8.PriceAlertCreate, S.PriceAlertCreate>>;
export type _M8_PriceAlertUpdate = Nessuno<SoloNelFrontend<M8.PriceAlertUpdate, S.PriceAlertUpdate>>;
export type _M8_Position = Nessuno<SoloNelFrontend<M8.Position, S.PositionOut>>;
export type _M8_PositionCreate = Nessuno<SoloNelFrontend<M8.PositionCreate, S.PositionCreate>>;
export type _M8_PositionUpdate = Nessuno<SoloNelFrontend<M8.PositionUpdate, S.PositionUpdate>>;
export type _M8_SpotlightCard = Nessuno<SoloNelFrontend<M8.SpotlightCard, S.SpotlightCardOut>>;
export type _M8_FundamentalsAnnual = Nessuno<SoloNelFrontend<M8.FundamentalsAnnual, S.FundamentalsAnnualOut>>;
export type _M8_FundamentalsQuarterly = Nessuno<SoloNelFrontend<M8.FundamentalsQuarterly, S.FundamentalsQuarterlyOut>>;
export type _M8_FundamentalsEarnings = Nessuno<SoloNelFrontend<M8.FundamentalsEarnings, S.FundamentalsEarningsOut>>;
export type _M8_MicroData = Nessuno<SoloNelFrontend<M8.MicroData, S.MicroDataOut>>;
export type _M8_InsiderTransaction = Nessuno<SoloNelFrontend<M8.InsiderTransaction, S.InsiderTransactionOut>>;
export type _M8_AnalystRating = Nessuno<SoloNelFrontend<M8.AnalystRating, S.AnalystRatingOut>>;
export type _M8_AnalystPriceTarget = Nessuno<SoloNelFrontend<M8.AnalystPriceTarget, S.AnalystPriceTargetOut>>;
export type _M8_CompanyProfile = Nessuno<SoloNelFrontend<M8.CompanyProfile, S.CompanyProfileOut>>;
export type _M8_Fundamentals = Nessuno<SoloNelFrontend<M8.Fundamentals, S.FundamentalsOut>>;
export type _M8_EtfHolding = Nessuno<SoloNelFrontend<M8.EtfHolding, S.EtfHoldingOut>>;
export type _M8_EtfHoldings = Nessuno<SoloNelFrontend<M8.EtfHoldings, S.EtfHoldingsOut>>;
export type _M8_SubScores = Nessuno<SoloNelFrontend<M8.SubScores, S.SubScoresOut>>;
export type _M8_StockScore = Nessuno<SoloNelFrontend<M8.StockScore, S.StockScoreOut>>;
export type _M8_TopPickItem = Nessuno<SoloNelFrontend<M8.TopPickItem, S.TopPickItemOut>>;
export type _M8_TopPicks = Nessuno<SoloNelFrontend<M8.TopPicks, S.TopPicksOut>>;
export type _M8_ScoreHistoryPoint = Nessuno<SoloNelFrontend<M8.ScoreHistoryPoint, S.ScoreHistoryPoint>>;
export type _M8_ScoreHistoryOut = Nessuno<SoloNelFrontend<M8.ScoreHistoryOut, S.ScoreHistoryOut>>;
export type _M8_EarningsEvent = Nessuno<SoloNelFrontend<M8.EarningsEvent, S.EarningsEventOut>>;
export type _M8_MacroEvent = Nessuno<SoloNelFrontend<M8.MacroEvent, S.MacroEventOut>>;
export type _M8_MacroRelease = Nessuno<SoloNelFrontend<M8.MacroRelease, S.MacroReleaseOut>>;
export type _M8_MacroSeriesDetail = Nessuno<SoloNelFrontend<M8.MacroSeriesDetail, S.MacroSeriesDetailOut>>;
export type _M8_Calendar = Nessuno<SoloNelFrontend<M8.Calendar, S.CalendarOut>>;
export type _M8_InstitutionalSummary = Nessuno<SoloNelFrontend<M8.InstitutionalSummary, S.InstitutionalSummaryOut>>;
export type _M8_HoldingDetail = Nessuno<SoloNelFrontend<M8.HoldingDetail, S.HoldingDetailOut>>;
export type _M8_InstitutionalDetail = Nessuno<SoloNelFrontend<M8.InstitutionalDetail, S.InstitutionalDetailOut>>;
export type _M8_TickerAggregate = Nessuno<SoloNelFrontend<M8.TickerAggregate, S.TickerAggregateOut>>;
export type _M8_ActionAggregate = Nessuno<SoloNelFrontend<M8.ActionAggregate, S.ActionAggregateOut>>;
export type _M8_AggregateStats = Nessuno<SoloNelFrontend<M8.AggregateStats, S.AggregateStatsOut>>;
export type _M8_TickerHolder = Nessuno<SoloNelFrontend<M8.TickerHolder, S.TickerHolderOut>>;
export type _M8_TickerHolders = Nessuno<SoloNelFrontend<M8.TickerHolders, S.TickerHoldersOut>>;
export type _M9_IndexStatus = Nessuno<SoloNelFrontend<M9.IndexStatus, S.IndexStatusOut>>;
export type _M9_CatalogStatus = Nessuno<SoloNelFrontend<M9.CatalogStatus, S.CatalogStatusOut>>;
export type _M10_EquityPoint = Nessuno<SoloNelFrontend<M10.EquityPoint, S.EquityPointOut>>;
export type _M10_EquityCurve = Nessuno<SoloNelFrontend<M10.EquityCurve, S.EquityCurveOut>>;
export type _M11_LiveAsset = Nessuno<SoloNelFrontend<M11.LiveAsset, S.LiveAsset>>;
export type _M12_LiveMover = Nessuno<SoloNelFrontend<M12.LiveMover, S.LiveMoverOut>>;
export type _M13_MarketDetail = Nessuno<SoloNelFrontend<M13.MarketDetail, S.MarketDetailOut>>;
export type _M14_TimeframeKpis = Nessuno<SoloNelFrontend<M14.TimeframeKpis, S.TimeframeKpisOut>>;
export type _M14_MultiTfKpis = Nessuno<SoloNelFrontend<M14.MultiTfKpis, S.MultiTfKpisOut>>;
export type _M15_CalibrationBucket = Nessuno<SoloNelFrontend<M15.CalibrationBucket, S.CalibrationBucketOut>>;
export type _M15_Calibration = Nessuno<SoloNelFrontend<M15.Calibration, S.CalibrationOut>>;
export type _M16_PhaseTiming = Nessuno<SoloNelFrontend<M16.PhaseTiming, S.PhaseTimingOut>>;
export type _M16_ScanRunSummary = Nessuno<SoloNelFrontend<M16.ScanRunSummary, S.ScanRunSummaryOut>>;
export type _M17_SectorStockRow = Nessuno<SoloNelFrontend<M17.SectorStockRow, S.SectorStockRow>>;
export type _M17_CountBucket = Nessuno<SoloNelFrontend<M17.CountBucket, S.CountBucket>>;
export type _M17_PillarAverages = Nessuno<SoloNelFrontend<M17.PillarAverages, S.PillarAverages>>;
export type _M17_SectorKpis = Nessuno<SoloNelFrontend<M17.SectorKpis, S.SectorKpis>>;
export type _M17_SectorDetail = Nessuno<SoloNelFrontend<M17.SectorDetail, S.SectorDetailOut>>;
export type _M17_SectorTrendPoint = Nessuno<SoloNelFrontend<M17.SectorTrendPoint, S.SectorTrendPoint>>;
export type _M17_SectorSummary = Nessuno<SoloNelFrontend<M17.SectorSummary, S.SectorSummary>>;
export type _M17_IndustryRow = Nessuno<SoloNelFrontend<M17.IndustryRow, S.IndustryRow>>;
export type _M17_SectorsOverview = Nessuno<SoloNelFrontend<M17.SectorsOverview, S.SectorsOverviewOut>>;
export type _M17_LeaderRow = Nessuno<SoloNelFrontend<M17.LeaderRow, S.LeaderRowOut>>;
export type _M17_Leaderboards = Nessuno<SoloNelFrontend<M17.Leaderboards, S.LeaderboardsOut>>;
export type _M18_Setup = Nessuno<SoloNelFrontend<M18.Setup, S.SetupOut>>;
