"""drop unique rules.watchlist_kind

Revision ID: 7e2e42691dff
Revises: 4841a82d3387
Create Date: 2026-05-02 17:59:48.216142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e2e42691dff'
down_revision: Union[str, Sequence[str], None] = '4841a82d3387'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rules', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_rules_watchlist_kind'), type_='unique')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rules', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_rules_watchlist_kind'), ['watchlist_id', 'kind'])

    # ### end Alembic commands ###
