"""alert engine schema

Revision ID: aabe2bc3256f
Revises: ff5bc449215b
Create Date: 2026-05-01 12:53:02.680845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aabe2bc3256f'
down_revision: Union[str, Sequence[str], None] = 'ff5bc449215b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ohlcv_daily',
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('high', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('low', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('close', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('stock_id', 'date')
    )
    with op.batch_alter_table('ohlcv_daily', schema=None) as batch_op:
        batch_op.create_index('ix_ohlcv_daily_date', ['date'], unique=False)

    op.create_table('rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('watchlist_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('params', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('watchlist_id', 'kind', name='uq_rules_watchlist_kind')
    )
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('trigger_price', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('snapshot', sa.Text(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index('ix_alerts_archived_at', ['archived_at'], unique=False)
        batch_op.create_index('ix_alerts_read_at', ['read_at'], unique=False)
        batch_op.create_index('ix_alerts_rule_id', ['rule_id'], unique=False)
        batch_op.create_index('ix_alerts_stock_id', ['stock_id'], unique=False)
        batch_op.create_index('ix_alerts_triggered_at', ['triggered_at'], unique=False)

    op.create_table('rule_states',
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('last_evaluation', sa.Boolean(), nullable=False),
    sa.Column('last_evaluated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rule_id', 'stock_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rule_states')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index('ix_alerts_triggered_at')
        batch_op.drop_index('ix_alerts_stock_id')
        batch_op.drop_index('ix_alerts_rule_id')
        batch_op.drop_index('ix_alerts_read_at')
        batch_op.drop_index('ix_alerts_archived_at')

    op.drop_table('alerts')
    op.drop_table('rules')
    with op.batch_alter_table('ohlcv_daily', schema=None) as batch_op:
        batch_op.drop_index('ix_ohlcv_daily_date')

    op.drop_table('ohlcv_daily')
    # ### end Alembic commands ###
